# Generated by Django 3.1 on 2021-09-14 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='categories',
            field=models.ManyToManyField(blank=True, to='items.Category'),
        ),
        migrations.AlterField(
            model_name='book',
            name='collections',
            field=models.ManyToManyField(blank=True, to='items.Collection'),
        ),
        migrations.AlterField(
            model_name='book',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='pictures'),
        ),
    ]
