# Generated by Django 3.1 on 2021-10-17 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_auto_20211017_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
