# Generated by Django 3.1 on 2021-10-30 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_employee_of_organization'),
        ('items', '0005_book_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('lost', 'Lost'), ('reserved', 'Reserved'), ('borrowed', 'Prêté'), ('available', 'disponible')], default='available', max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='book',
            unique_together={('isbn', 'organization', 'title')},
        ),
    ]
