# Generated by Django 3.1 on 2021-11-07 21:58

from django.db import migrations, models
import src.items.models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_auto_20211030_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='slug',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='categories',
            field=models.ManyToManyField(blank=True, null=True, to='items.Category'),
        ),
        migrations.AlterField(
            model_name='book',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=src.items.models.path_and_rename),
        ),
    ]
