# Generated by Django 3.1 on 2021-11-07 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0008_auto_20211107_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='slug',
            field=models.CharField(default='foo', max_length=255),
            preserve_default=False,
        ),
    ]
