# Generated by Django 3.2.9 on 2021-11-11 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0010_auto_20211111_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lending',
            name='allowance_days',
            field=models.IntegerField(blank=True, default=31),
        ),
    ]
