# Generated by Django 3.2.9 on 2021-11-11 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0011_alter_lending_allowance_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='status',
        ),
    ]
