# Generated by Django 3.2.9 on 2022-01-28 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0013_alter_book_published_year'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name']},
        ),
    ]
