# Generated by Django 4.0.6 on 2022-09-08 20:57
from django.contrib.postgres.operations import CreateExtension
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0014_auto_20220128_0037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lending',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lendings', to='items.book'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['author'], name='items_book_author_892de8_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['title'], name='items_book_title_830b2d_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['isbn'], name='items_book_isbn_0120b3_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['organization_id', 'author', 'title', 'isbn'], name='items_book_organiz_0f4142_idx'),
        ),
        CreateExtension(name='unaccent'),
    ]
